version: "3"

volumes:
  node_modules:

networks:
  my-network:
    driver: bridge

services:
  ws_react:
    build:
      context: .
      dockerfile: Dockerfile_react
    container_name: ${NODE_CONTAINER_NAME}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    volumes:
      - .:${APP_DIRECTORY}
      - node_modules:${APP_DIRECTORY}${MODULES_DIRECTORY}
    networks:
      - my-network
